version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfilee
    container_name: web
    ports:
      - "35000:6000"
    networks:
      - my_network

  web1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web1
    ports:
      - "35001:6000"
    networks:
      - my_network

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web2
    ports:
      - "35002:6000"
    networks:
      - my_network
  web3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web3
    ports:
      - "35003:6000"
    networks:
      - my_network
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
    networks:
      - my_network

volumes:
  mongodb:
  mongodb_config:

networks:
  my_network: